// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgXrVBWrg8NIau2ciUFa7MXB86bKpUGFQ',
    appId: '1:929210020910:web:96256ec296a97015015bbf',
    messagingSenderId: '929210020910',
    projectId: 'gestionaccident-6d003',
    authDomain: 'gestionaccident-6d003.firebaseapp.com',
    databaseURL: 'https://gestionaccident-6d003-default-rtdb.firebaseio.com',
    storageBucket: 'gestionaccident-6d003.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJV-b96wUFF6f4k9hgp8-n3CBZUg2sCwc',
    appId: '1:929210020910:android:31564bc35f4e0d89015bbf',
    messagingSenderId: '929210020910',
    projectId: 'gestionaccident-6d003',
    databaseURL: 'https://gestionaccident-6d003-default-rtdb.firebaseio.com',
    storageBucket: 'gestionaccident-6d003.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNDtTvMf2JcRDLk83p_jKlL83ZldLXKQc',
    appId: '1:929210020910:ios:13720d023ec43d2c015bbf',
    messagingSenderId: '929210020910',
    projectId: 'gestionaccident-6d003',
    databaseURL: 'https://gestionaccident-6d003-default-rtdb.firebaseio.com',
    storageBucket: 'gestionaccident-6d003.appspot.com',
    iosBundleId: 'com.example.gestionAcc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNDtTvMf2JcRDLk83p_jKlL83ZldLXKQc',
    appId: '1:929210020910:ios:13720d023ec43d2c015bbf',
    messagingSenderId: '929210020910',
    projectId: 'gestionaccident-6d003',
    databaseURL: 'https://gestionaccident-6d003-default-rtdb.firebaseio.com',
    storageBucket: 'gestionaccident-6d003.appspot.com',
    iosBundleId: 'com.example.gestionAcc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgXrVBWrg8NIau2ciUFa7MXB86bKpUGFQ',
    appId: '1:929210020910:web:c36168e75e1383b4015bbf',
    messagingSenderId: '929210020910',
    projectId: 'gestionaccident-6d003',
    authDomain: 'gestionaccident-6d003.firebaseapp.com',
    databaseURL: 'https://gestionaccident-6d003-default-rtdb.firebaseio.com',
    storageBucket: 'gestionaccident-6d003.appspot.com',
  );
}
